services:
  app:
    build: .
    container_name: challenge-java-app
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_DB=postgres-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_URL=jdbc:postgresql://db:5432/postgres-db
    ports:
      - "5432:5432"
    restart: always